"""Base classes for red team test plugins.

Provides :class:`PluginContext`, the abstract :class:`RedteamPluginBase`,
and the :func:`discover` entry-point function.
"""

from __future__ import annotations

import itertools
import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, TypeVar

from jinja2 import Template as Jinja2Template

from kitty.redteam.plugins.manifest import PluginManifest

logger = logging.getLogger(__name__)


@dataclass
class PluginContext:
    """Runtime context passed to a plugin when generating tests.

    Attributes:
        target_purpose: Description of the target system's purpose.
        target_type: Type of target (e.g. ``"chat"``, ``"completion"``).
        entities: List of relevant entities (users, documents, etc.).
        language: Target language code (e.g. ``"zh-CN"``, ``"en"``).
        provider_id: Identifier of the provider being tested.
    """

    target_purpose: str = ""
    target_type: str = ""
    entities: list[str] = field(default_factory=list)
    language: str = "en"
    provider_id: str = ""


T = TypeVar("T", bound="RedteamPluginBase")


class TestCase:
    """A single test case generated by a red team plugin.

    Attributes:
        prompt: The prompt text to send to the target.
        plugin_id: ID of the plugin that generated this test.
        strategy_id: ID of the strategy applied, if any.
        assertions: List of assertion rule dictionaries.
        metadata: Arbitrary metadata attached to the test.
        severity: Severity level for this test.
        vars: Variable bindings used to render the template.
    """

    def __init__(
        self,
        prompt: str,
        plugin_id: str = "",
        strategy_id: str = "",
        assertions: list[dict[str, Any]] | None = None,
        metadata: dict[str, Any] | None = None,
        severity: str = "medium",
        vars: dict[str, str] | None = None,
    ) -> None:
        """Initialize a TestCase.

        Args:
            prompt: The rendered prompt text.
            plugin_id: Source plugin identifier.
            strategy_id: Applied strategy identifier.
            assertions: Assertions to validate the response.
            metadata: Additional metadata.
            severity: Finding severity level.
            vars: Template variable bindings used.
        """
        self.prompt = prompt
        self.plugin_id = plugin_id
        self.strategy_id = strategy_id
        self.assertions = assertions or []
        self.metadata = metadata or {}
        self.severity = severity
        self.vars = vars or {}

    def __repr__(self) -> str:
        """Return a short representation of the test case."""
        return (
            f"TestCase(plugin_id={self.plugin_id!r}, "
            f"strategy_id={self.strategy_id!r}, "
            f"prompt={self.prompt[:50]!r}...)"
        )


class RedteamPluginBase(ABC):
    """Abstract base class for all red team test plugins.

    Subclasses must set :attr:`manifest` as a class attribute with a
    :class:`PluginManifest` instance describing the plugin.

    The default :meth:`generate_tests` implementation renders each
    template from :meth:`get_templates` with every combination of
    variables from :meth:`get_vars` in a round-robin fashion, up to
    ``num_tests`` test cases.
    """

    manifest: PluginManifest
    """Plugin manifest describing this plugin's metadata and configuration."""

    SUPPORTED_PROVIDERS: list[str] = []
    """List of supported provider IDs. Empty means all providers are supported."""

    @property
    def plugin_id(self) -> str:
        """Return the unique identifier for this plugin."""
        return self.manifest.id

    def get_templates(self, context: PluginContext) -> list[str]:
        """Return the list of template strings to render.

        Override this method to dynamically select templates based on
        the runtime context.

        Args:
            context: The plugin runtime context.

        Returns:
            A list of Jinja2 template strings.
        """
        return list(self.manifest.templates)

    def get_assertions(self, context: PluginContext) -> list[dict[str, Any]]:
        """Return the list of assertion dictionaries for generated tests.

        Override this method to dynamically adjust assertions based on
        the runtime context.

        Args:
            context: The plugin runtime context.

        Returns:
            A list of assertion rule dictionaries.
        """
        return [dict(a) for a in self.manifest.assertions]

    def get_vars(self, context: PluginContext) -> dict[str, list[str]]:
        """Return the variable dictionary for template rendering.

        Override this method to dynamically supply variable values
        based on the runtime context.

        Args:
            context: The plugin runtime context.

        Returns:
            A dict mapping variable names to lists of possible values.
        """
        return dict(self.manifest.vars)

    async def on_loaded(self) -> None:
        """Called after the plugin is loaded and registered.

        Subclasses can override this to perform async initialization
        such as loading external data or validating configuration.
        """

    async def generate_tests(
        self,
        context: PluginContext,
        num_tests: int | None = None,
    ) -> list[TestCase]:
        """Generate a list of test cases for the given context.

        The default implementation cycles through all templates and
        all variable combinations in round-robin order up to the
        specified limit.

        Args:
            context: Runtime context for test generation.
            num_tests: Maximum number of tests to generate. If ``None``,
                the plugin manifest's ``num_tests`` is used.

        Returns:
            A list of generated :class:`TestCase` instances.
        """
        num_tests = num_tests or self.manifest.num_tests
        templates = self.get_templates(context)
        assertions = self.get_assertions(context)
        template_vars = self.get_vars(context)

        if not templates:
            logger.warning("Plugin %s has no templates; returning empty test list", self.plugin_id)
            return []

        # Build a list of variable combinations (round-robin across all variables).
        var_keys = list(template_vars.keys())
        var_values: list[list[str]] = [template_vars[k] for k in var_keys]

        tests: list[TestCase] = []
        template_cycle = itertools.cycle(templates)

        for i in range(num_tests):
            template_str = next(template_cycle)
            # Build variable bindings for this iteration (round-robin each variable).
            bindings: dict[str, str] = {}
            for idx, key in enumerate(var_keys):
                values = var_values[idx]
                bindings[key] = values[i % len(values)] if values else ""

            try:
                jinja_template = Jinja2Template(template_str)
                prompt = jinja_template.render(**bindings)
            except Exception as exc:
                logger.warning(
                    "Failed to render template %r with vars %r: %s",
                    template_str,
                    bindings,
                    exc,
                )
                prompt = template_str

            tests.append(
                TestCase(
                    prompt=prompt,
                    plugin_id=self.plugin_id,
                    assertions=[dict(a) for a in assertions],
                    metadata={"plugin_id": self.plugin_id},
                    severity=self.manifest.severity.value,
                    vars=dict(bindings),
                )
            )

        return tests


def discover() -> dict[str, type[RedteamPluginBase]]:
    """Discover all available plugin classes.

    This function is intended to be called by entry-point consumers.
    It scans the built-in plugin directories and user plugin directories,
    returning a mapping of plugin IDs to their factory classes.

    Returns:
        A dictionary mapping plugin IDs to plugin classes.
    """
    from kitty.redteam.plugins.registry import PluginRegistry

    return PluginRegistry.list_all()  # type: ignore[return-value]
