repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff-format
        args: [--line-length=100]
      - id: ruff
        args: [--fix, --line-length=100]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--strict, --python-version=3.10]
        additional_dependencies:
          - pydantic>=2.10,<3
          - sqlalchemy[asyncio]>=2.0,<3
          - types-PyYAML
          - types-diskcache
          - types-redis

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-toml
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.0"
    hooks:
      - id: poetry-check
        name: poetry-lock-check
        args: [--lock]
        verbose: true
